name: Draft Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read version
        id: v
        run: echo "ver=$(cat VERSION | tr -d '\n')" >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release v${{ steps.v.outputs.ver }}
          tag_name: v${{ steps.v.outputs.ver }}
          body_path: RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
